#!/usr/bin/env zsh

# Get this file's current directory and source Dima's zshrc from there
A_ZSH_DOTFILES="$( dirname "$( readlink -f "$0" )" )"

DOTFILES_SYNC_LAST_WORKING_DIR=1

_dotfiles_customizations() {
  for script in functions plugins aliases; do
    source "$A_ZSH_DOTFILES/$script.zsh"
  done

  if [[ -d "$A_ZSH_DOTFILES/custom" ]]; then
    for script in $A_ZSH_DOTFILES/custom/*.zsh; do
      source "$script"
    done
  fi

  if [[ -n "$DOTFILES_SYNC_LAST_WORKING_DIR" ]]; then
    sync_working_dir_load
  fi
}

source $A_ZSH_DOTFILES/../dmitmel-dotfiles/zsh/zshrc
